org: carlosgil
app: typescript-http-api
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action:
          - dynamodb:*
      Resource:
          - arn:aws:dynamodb:us-east-1:923195502435:table/MoviesTable

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  addMovie:
    handler: addMovie.addMovie
    events:
      - httpApi:
          path: /movies
          method: post   
  getMovies:
    handler: getMovies.getMovies
    events:
      - httpApi:
          path: /movies
          method: get 
  getMovie:
    handler: getMovie.getMovie
    events:
      - httpApi:
          path: /movie/{id}
          method: get        
  updateMovie:
    handler: updateMovie.updateMovie
    events:
      - httpApi:
          path: /movie/{id}
          method: put    
  deleteMovie:
    handler: deleteMovie.deleteMovie
    events:
      - httpApi:
          path: /movie/{id}
          method: delete                                    

resources:
  Resources:
    MoviesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MoviesTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
        KeySchema:
            - AttributeName: id
              KeyType: HASH          
